spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    password: TIGER
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: SCOTT
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true